services:
  websocket_app:
    # Build the image using the Dockerfile in the current directory (.)
    build:
      context: .
      dockerfile: Dockerfile
    # Name the container for easier identification
    container_name: speech_websocket_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app 
    restart: unless-stopped